(ns metadata-mongo.fields)

(def field-list
  '("Aperture Value"
    "Artist"
    "By-Line"
    "Camera Owner Name"
    "Caption/Abstract"
    "Color Space"
    "Copyright"
    "Copyright Notice"
    "Data Precision"
    "Date/Time Digitized"
    "Date/Time Original"
    "Exposure Bias Value"
    "Exposure Mode"
    "Exposure Program"
    "Exposure Time"
    "F-Number"
    "File Modified Date"
    "Flash"
    "Focal Length"
    "Focal Length 35"
    "ISO Speed Ratings"
    "Image Height"
    "Image Width"
    "Keywords"
    "Lens"
    "Make"
    "Metering Mode"
    "Model"
    "Object Name"
    "Rating"
    "Reference Date"
    "Software"
    "Special Instructions"
    "User Comment"
    "White Balance"
    "White Balance Mode"))

(comment
  field-list)
